# Generated by Django 5.2.4 on 2025-07-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
