# Generated by Django 5.2.4 on 2025-07-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_display_name_manualcodinglog_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagestat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='languagestat',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='user',
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
        migrations.DeleteModel(
            name='LanguageStat',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
